on:
  push:
    branches:    
      - 'main'
  pull_request:
    types:
      - closed
    branches:    
      - 'main'
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: macos-12
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
